### PR TITLE
Add Qt6 support

### LINKED ISSUE #1: Support sddm qt6

### PR DESCRIPTION
**Pull request by plattfot**
Minor changes needed, e.g. using `file:` to make Qt look in the right location.  And explicit define `event` for the key press event.

Unclear if this will fix #1 it looks fine with in `--test-mode`.

### CODE REVIEW

**Comment by RJSent** [comment]
I still observe the theme failing to apply on this branch. Here's the snippet from my configuration:

```
(define test-guix-simplyblack-theme-qt6
  (options->transformation
   '((with-branch . "guix-simplyblack-sddm-theme=qt6_support"))))

(operating-system
 ...
 (services
  ...
  (list (service sddm-service-type
                 (sddm-configuration
                  (theme "guix-simplyblack-sddm")
                  (themes-directory (file-append (test-guix-simplyblack-theme-qt6 guix-simplyblack-sddm-theme) "/share/sddm/themes"))))
```

`/var/log/sddm.log` isn't helpful. It reports the same error as mentioned in #1.

```
[18:12:40.468] (II) DAEMON: Loading theme configuration from "/gnu/store/46lww7j5mi0z2d9bykflywwgjrd7bn4n-guix-simplyblack-sddm-theme-git.qt6_support/share/sddm/themes/guix-simplyblack-sddm/theme.conf"
[18:12:40.468] (WW) DAEMON: The theme at "/gnu/store/46lww7j5mi0z2d9bykflywwgjrd7bn4n-guix-simplyblack-sddm-theme-git.qt6_support/share/sddm/themes/guix-simplyblack-sddm" requires missing "/gnu/store/vgg1gspby7kr94gl479mhzwaswpz5qv6-sddm-0.21.0/bin/sddm-greeter" . Using fallback theme.
[18:12:40.468] (II) DAEMON: Loaded empty theme configuration
```

Edit: There is a `/gnu/store/blah-sddm-0.21.0/bin/sddm-greeter-qt6` file, perhaps a path needs updating?

**Comment by plattfot** [comment]
> Edit: There is a /gnu/store/blah-sddm-0.21.0/bin/sddm-greeter-qt6 file, perhaps a path needs updating?

I think you are on to something. I don't see where the theme is requesting the `sddm-greeter` though. Neither the QML code or the build is using it. And the final derivation of the package does not have any mentioned of it either (did `rg sddm-greeter $(guix build guix-simplyblack-sddm-theme)`). Maybe I need to bump up the `import SddmComponents 2.0` or something.

I will have time to debug it this weekend. This time I'll spin up a VM as just using the test mode in the `sddm-greeter-qt6` did not catch anything. And thank you for the configure snippet, will be handy for the VM.

**Comment by plattfot** [comment]
Ok, I figured out the issue with it not popping up.  Turns out you need to explicitly tell sddm that the theme is for Qt 6 otherwise it will assume Qt 5.

So now when I run it via a VM the theme shows up.  However the background is white in my VM. It is black when running the `sddm-greeter-qt6` locally.  So still need to figure out why that's happening but I'm getting closer to solving this!

**Comment by plattfot** [comment]
Ok, I think I might have ironed out the last issue of getting this to run with Qt6. Updated the build to replace all `file:` paths with the absolute path to the store. Works both when running the greeter locally and in my VM. I'll merge this tomorrow then I'll need to create a patch in the guix main channel to update the package definition to fix the paths. After that this should be working somewhat.

**Pull request merged**
